---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

name: Рабочий процесс CMake GitHub

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERBOSE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os: [macos-15, macos-15-intel, ubuntu-latest, windows-latest]
        c_compiler: [cl, clang, gcc, icx, lcc, occ, pgcc, pocc, suncc, tcc]
        build_type: [Release]
        exclude:
          - {os: macos-15, c_compiler: cl}
          - {os: macos-15, c_compiler: icx}
          - {os: macos-15, c_compiler: lcc}
          - {os: macos-15, c_compiler: occ}
          - {os: macos-15, c_compiler: pgcc}
          - {os: macos-15, c_compiler: pocc}
          - {os: macos-15, c_compiler: suncc}
          - {os: macos-15, c_compiler: tcc}
          - {os: macos-15-intel, c_compiler: cl}
          - {os: macos-15-intel, c_compiler: icx}
          - {os: macos-15-intel, c_compiler: lcc}
          - {os: macos-15-intel, c_compiler: occ}
          - {os: macos-15-intel, c_compiler: pgcc}
          - {os: macos-15-intel, c_compiler: pocc}
          - {os: macos-15-intel, c_compiler: suncc}
          - {os: macos-15-intel, c_compiler: tcc}
          - {os: ubuntu-latest, c_compiler: cl}
          - {os: ubuntu-latest, c_compiler: occ}
          - {os: ubuntu-latest, c_compiler: pocc}
          - {os: windows-latest, c_compiler: icx}
          - {os: windows-latest, c_compiler: lcc}
          - {os: windows-latest, c_compiler: pgcc}
          - {os: windows-latest, c_compiler: suncc}
          - {c_compiler: pgcc}  # TODO: установка для GitHub
          - {c_compiler: suncc}  # TODO: установка для GitHub
          - {c_compiler: tcc}  # TODO: установка для GitHub
          # Давим из конфигурации репозитория
          - os: ${{ case(contains(vars.DISABLE, ' macos-15,'),
              'macos-15', 'enable-os1') }}
          - os: ${{ case(contains(vars.DISABLE, ' macos-15-intel,'),
              'macos-15-intel', 'enable-os2') }}
          - os: ${{ case(contains(vars.DISABLE, ' ubuntu-latest,'),
              'ubuntu-latest', 'enable-os3') }}
          - os: ${{ case(contains(vars.DISABLE, ' windows-latest,'),
              'windows-latest', 'enable-os4') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' cl,'),
              'cl', 'enable-c1') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' clang,'),
              'clang', 'enable-c2') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' gcc,'),
              'gcc', 'enable-c3') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' icx,'),
              'icx', 'enable-c4') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' lcc,'),
              'lcc', 'enable-c5') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' occ,'),
              'occ', 'enable-c6') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' pgcc,'),
              'pgcc', 'enable-c7') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' pocc,'),
              'pocc', 'enable-c8') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' suncc,'),
              'suncc', 'enable-c9') }}
          - c_compiler: ${{ case(contains(vars.DISABLE, ' tcc,'),
              'tcc', 'enable-c10') }}
        # Но всегда должна быть
        include: [{os: ubuntu-latest, c_compiler: gcc}]

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        if: runner.os != 'Windows'  # И так притормаживает
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          python -m yamllint .

      - if: matrix.c_compiler == 'cl'
        uses: ilammy/msvc-dev-cmd@v1
      - if: matrix.c_compiler == 'icx'
        uses: Serge3leo/oneapi-setup@v0
        with:
          # version: 2025.1
          verbose: true

      - if: matrix.c_compiler == 'lcc'
        uses: Serge3leo/lcc-env-action@lcc-1.29.16
        #uses: Serge3leo/lcc-env-action@v0
        # with:
        #   lcc_version: 1.27.23
        #   qemu_e2k_version: "1.0"
      - if: matrix.c_compiler == 'occ'
        uses: Serge3leo/orangec-msys2@v0
        with:
          # version: 6.73.1
          verbose: true
          msystem: skip  # Может и так ничего

      - if: matrix.c_compiler == 'pocc'
        uses: Serge3leo/pellesc-msys2@space14rc
        # uses: Serge3leo/pellesc-msys2@v0
        with:
          version: 14.0-rc1-git-lfs
          # version: 12.0.2  # WARNING: Needed windows-2022
          verbose: true

      - name: Имена компиляторов с версиями, если необходимо
        shell: bash
        run: |
          build_type="${{ matrix.build_type }}"
          if [ -z "$build_type" ] ; then
            build_type=Release
          fi
          c_compiler="${{ matrix.c_compiler }}"
          if [ -n "$VERBOSE" ] ; then
            for d in /usr/bin /usr/local/bin /opt/local/bin ; do
              ls -l $d/*"$c_compiler"* || true
            done
          fi
          case "$c_compiler" in
          clang)
            c_compiler=""
            # TODO macOS $(brew --prefix llvm@18)/bin/clang
            for c in clang{-{18,17,16},} ; do
              if type $c > /dev/null ; then
                c_compiler=$c
                cxx=`echo $c | sed 's/clang/clang++/'`
                if type $cxx > /dev/null ; then
                  break
                fi
                if type "$cxx++" > /dev/null ; then
                  break
                fi
              fi
            done
            ;;
          gcc)
            c_compiler=""
            for c in gcc{-{15,14,13},} ; do
              if type $c > /dev/null ; then
                c_compiler=$c
                cxx=`echo $c | sed 's/gcc/g++/'`
                if type $cxx > /dev/null ; then
                  break
                fi
                if type "$cxx++" > /dev/null ; then
                  break
                fi
              fi
            done
            ;;
          icx)
            cxx=icpx
            ;;
          lcc)
            cxx=l++
            cross_emul=e2k
            cmake_add="-DCMAKE_CROSSCOMPILING=ON \
                       -DCMAKE_SYSTEM_NAME=Generic-ELF \
                       -DCMAKE_CROSSCOMPILING_EMULATOR=$cross_emul"
            ;;
          occ)
            cxx=occ
            gen_flags="-G 'MSYS Makefiles'"
            ;;
          pgcc)
            cxx=pgc++
            ;;
          pocc)
            cxx=cxx_disable
            gen_flags="-G 'MSYS Makefiles'"
            ;;
          suncc)
            cxx=sunCC
            ;;
          tcc)
            cxx=cxx_disable
            ;;
          *)
            cxx="$c_compiler"
          esac
          if [ -z "$cxx" ] ; then
            echo "Неудача определения C++-компилятора" 1>&2
            exit 5
          fi
          if [ "$cxx" != "cxx_disable" ] ; then
            cxx_flags="-DCMAKE_CXX_COMPILER=$cxx"
          else
            cxx_flags="-DLEARN_CMAKE_CXX_ENABLE=OFF"
          fi
          cat >> $GITHUB_ENV <<_end_of_github_env_
          build_type=$build_type
          c_compiler=$c_compiler
          cxx_flags=$cxx_flags
          gen_flags=$gen_flags
          cross_emul=$cross_emul
          cmake_add=$cmake_add
          _end_of_github_env_

      - name: Ставим заплатки
        shell: bash
        run: |
          type sudo && {
            SUDO=sudo
          }
          cmake -P workarounds/detect.cmake || {
            $SUDO cmake -P workarounds/install.cmake
          }
          cmake -P workarounds/detect.cmake

      - name: Конфигурация
        shell: bash
        run: >
          eval "cmake -B build
          -DCMAKE_C_COMPILER=\"$c_compiler\" $cxx_flags $gen_flags
          -DCMAKE_BUILD_TYPE=$build_type $cmake_add -S ."

      - name: Сборка
        shell: bash
        run: cmake --build build --config $build_type

      - name: Тесты
        shell: bash
        run: ctest --output-on-failure --build-config $build_type
          --test-dir build

      - name: Контрольный запуск
        shell: bash
        run: |
          if [ "$c_compiler" = "cl" ] ; then
            d="$build_type"
          fi
          for h in build/hello/$d/hello{,++}{,.exe,.elf} ; do
            if [ -f "$h" ] ; then
              $cross_emul "$h"
            fi
          done
